name: CI

on:
  push:
    branches: [ development, release ]
  pull_request:
    branches: [ development, release ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v13
      with:
        name: nitrous-os
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Check flake
      run: nix flake check --print-build-logs
    - name: Check formatting
      run: nix fmt -- --check .
    - name: Build minimal system
      run: nix build .#nixosConfigurations.minimal.config.system.build.toplevel --print-build-logs