name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v13
      with:
        name: nitrous-os
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: Build ISOs
      run: |
        nix build .#desktop-iso --print-build-logs
        nix build .#server-iso --print-build-logs
        nix build .#minimal-iso --print-build-logs
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          result/*.iso
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}